### ISSUE TITLE
Round corners of maximized windows

### ISSUE THREAD

**Issue by Quantenzitrone** [yilozt/mutter-rounded#54]
Is it possible, and if not, could it be implemented, to also round maximized windows?
I made some conky widgets to serve as useless gaps for aesthetic purposes.
So if I maximize a window (or if it maximizes itself) it leaves a gap like this:
![Screenshot from 2022-03-30 18-35-01](https://user-images.githubusercontent.com/74491719/160886218-e357ce81-0f83-47d0-9633-5651af4dcf12.png)

I think you see what the problem here is. I want it to look like this:
![Screenshot from 2022-03-30 18-37-37](https://user-images.githubusercontent.com/74491719/160886710-29eec2d2-48a1-4679-b307-9b563a2ed2a7.png)

**Comment by Quantenzitrone** [comment]
I managed to do it with the extension [Useless Gaps](https://extensions.gnome.org/extension/4684/useless-gaps/).
Should I close this issue?

**Comment by JustCryen** [comment]
I happened to stumble on this thread while searching for something else and I feel like I should mention that there's already an option to round the maximized windows.
![Screenshot from 2022-07-06 21-12-37](https://user-images.githubusercontent.com/41633661/177625986-af54cbd3-8efe-4ada-9c83-af05c7c21af9.png)
Since this issue was created in March and it's already July, maybe it was implemented in this time span.
I just don't know why it's not marked as solved already.

**Comment by JustCryen** [comment]
Thanks!

Can you just tell me what did you use to make the bottom of the screen rounded as well?
Is that just a wallpaper or something else?

**Comment by quantenzitrone** [comment]
im not using gnome anymore but i think it was an extension

**Comment by quantenzitrone** [comment]
but honestly a wallpaper would do the job too
